# Generated by Django 5.0.4 on 2024-04-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_placeimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Позиция'),
        ),
    ]
